### ISSUE TITLE
[AI] 여러가지 방식을 찾고 적용시켜 mAP 85%까지 높이기

### ISSUE THREAD

**Issue by fayej1221** [whdms2008/FarmSecurity#58]
# 1. 71% -> 76% 향상
- 416x416 모든 데이터 크기 resize
- resize한 것에 대한 이미지 파일 좌표 수정
- 해상도 높이기(bilateralFilter)
- cfg 파일 수정
- animal, bird, human 데이터 클래스 별로 train,vaild,test 셋 나누기
- yolov4에 대한 정확도 올리기 적용(cfg 수정)

## 1.2. 71% -> 76% 비교
- test_video들로 비교 영상 제작

# 2. data augmentation 이용해서 mAP 향상시키기 
### (https://github.com/whdms2008/FarmSecurity/issues/57)
-> 1, 2에서 한 것은 train mAP가 82.4%, test mAP가 76.82%(대략 77%)인 것을 감안했을 때
Overfitting은 아니지만 만족할 test mAP가 나오지 못해 data set을 더 늘리기로 함
- 원래 각각 250장(총 750장) -> 각각 750장(총 2250장)
- animal: 박창영, bird: 조은, human: 진민주가 맡아서 라벨링

## 2.1. 76% -> 88%로 향상
- animal: 0.94, bird: 0.78, human: 0.91
- yolo가 인식한 데이터를 확인 해본 결과 bird는 라벨링 다시하기로 함

## 2.2 bird 라벨링 재 진행 후 88% -> 88.12%로 향상,,
- animal: 0.92, bird:0.80, human: 0.92
- yolo 자체가 새 떼를 인식하기 어려워하니,, Stop하기로 함

# [yolo 한계]

YOLO는 영상을 7x7 의 그리드셀로 분할하여 각 그리드 셀을 중심으로 하는 각종 크기의 오브젝트에 대해서 경계박스 후보를 2개 예측한다.

R-CNN 계열은 후보를 1천개 이상 제안하는것에 비해 YOLO는 총 7x7x2 = 98개의 후보를 제안하므로 이로 인해 성능이 떨어진다. 

그래서 한 오브젝트 주변에 여러개의 오브젝트가 있을 때 검출을 잘 못한다.

예를 들면 새떼처럼 조그만 오브젝트들이 모여 있는 경우이다.

영상에서 작게 나타난 새 크기에 비해 그리드 셀은 상대적으로 너무 크다.

같은 이유로 셀 하나 안에 오브젝트가 여러개 있으면 최대 2개까지밖에 예측을 못한다
[출처] [YOLO, Object Detection Network ](https://blog.naver.com/sogangori/220993971883)|작성자 [sogangori](https://blog.naver.com/sogangori)

**Comment by freenozero** [comment]
1. 71% -> 76% 향상
- 416x416 모든 데이터 크기 resize
- resize한 것에 대한 이미지 파일 좌표 수정
- 해상도 높이기(bilateralFilter)
- cfg 파일 수정
- animal, bird, human 데이터 클래스 별로 train,vaild,test 셋 나누기
- yolov4에 대한 정확도 올리기 적용(cfg 수정)
